config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/accounts/index', to: 'accounts#index', as: 'accounts'
  get '/accounts', to: 'accounts#index', as: 'accounts_list'
  get '/accounts/new', to: 'accounts#new', as: 'new_account'
  post '/accounts/create', to: 'accounts#create', as: 'account_create'
  get '/accounts/:id', to: 'accounts#show', as: 'account'
  get '/accounts/:id/new_deposit', to: 'accounts#new_deposit', as: 'new_deposit'
  get '/accounts/:id/new_withdraw', to: 'accounts#new_withdraw', as: 'new_withdraw'
  post '/accounts/:id/deposit', to: 'accounts#deposit', as: 'deposit'
  post '/accounts/:id/withdraw', to: 'accounts#withdraw', as: 'withdraw'

  root to: 'accounts#index'
end

app/models/account.rb
# model account
class Account < ApplicationRecord
  has_many :transactions

  def deposit(amount)
    ActiveRecord::Base.transaction do
      transaction = Transaction.create(account_id: id, amount: amount)
      self.balance = [] if balance.nil?
      self.balance += transaction.amount
      save!
    end
  end

  def withdraw(amount)
    ActiveRecord::Base.transaction do
      transaction = Transaction.create(account_id: id, amount: -amount.to_i)
      self.balance = [] if self.balance.nil?
      self.balance += transaction.amount
      save!
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
# model transaction
class Transaction < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/accounts_controller.rb
# accounts controller
class AccountsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @accounts = Account.where(['user_id = ?', current_user.id])
  end

  def show
    @account = Account.find_by(id: params[:id])
  end

  def create
    Account.create(no: params[:no], balance: 0, user_id: current_user.id)
    redirect_to action: 'index'
  end

  def deposit
    account = Account.find(params[:id])
    account.deposit(params[:amount])
    redirect_to account_url(account)
  end

  def withdraw
    account = Account.find(params[:id])
    account.withdraw(params[:amount])
    redirect_to account_url(account)
  end

  def new
    render :new
  end

  def new_withdraw
    @account = Account.find(params[:id])
  end

  def new_deposit
    @account = Account.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/accounts/index.html.erb
<div class="container">
    <h1 class="title">Accounts</h1>
    <h2 class="subtitle">
        Accounts of User
    </h2>
    <div class="mt-4">
        <%= link_to 'Create Account', new_account_path, :class => 'button is-link' %>
    </div>
    <div class="columns mt-4">
        <% @accounts.each do |account| %>
        <div class="column is-one-third">
            <div class="card">
                <div class="card-content">
                    <div class="content">
                        <div class="title"><%= account.no %></div>
                        <div class="subtitle">Available balance <%= account.balance %></div>
                    </div>
                </div>
                <footer class="card-footer">
                    <%= link_to 'View', account_path(account), :class => 'card-footer-item' %>
                    <%= link_to 'Deposit', new_deposit_path(account), :class => 'card-footer-item' %>
                    <%= link_to 'Withdraw', new_withdraw_path(account), :class => 'card-footer-item' %>
                </footer>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/accounts/new.html.erb
<div class="container">
    <h1 class="title">Create account</h1>
    <h2 class="subtitle">
        Create an account
    </h2>
    <div class="mt-4">
        <%= link_to 'Back to Home', accounts_path, :class => 'button is-link' %>
    </div>
    <div class="columns mt-6">
        <div class="column is-4">
            <div class="card">
                <div class="card-header">
                    <div class="card-header-title">
                        Create an account
                    </div>
                </div>
                <div class="card-content">
                    <%= form_with url: account_create_path, method: :post do |form| %>
                    <div class="field">
                        <%= form.label :no, "Account No", :class => 'label' %>
                        <div class="control">
                            <%= form.text_field :no, :class => 'input' %>
                        </div>
                        <p class="help">Please enter the account no</p>
                    </div>
                    <%= form.submit "Create", :class => 'button' %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/accounts/new_deposit.html.erb
<div class="container">
    <h1 class="title">Deposit</h1>
    <h2 class="subtitle">
        Make a deposit
    </h2>
    <div class="mt-4">
        <%= link_to 'Back to the account', account_path(@account), :class => 'button is-link' %>
    </div>
    <div class="columns mt-6">
        <div class="column is-4">
            <div class="card">
                <div class="card-header">
                    <div class="card-header-title">
                        Make a deposit
                    </div>
                </div>
                <div class="card-content">
                    <%= form_with url: deposit_path(@account), method: :post do |form| %>
                    <div class="field">
                        <%= form.label :no, "Amount", :class => 'label' %>
                        <div class="control">
                            <%= form.text_field :amount, :class => 'input' %>
                        </div>
                        <p class="help">Please enter the amount</p>
                    </div>
                    <%= form.submit "Deposit", :class => 'button' %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/accounts/new_withdraw.html.erb
<div class="container">
    <h1 class="title">Withdraw</h1>
    <h2 class="subtitle">
        Make a withdraw
    </h2>
    <div class="mt-4">
        <%= link_to 'Back to the account', account_path(@account), :class => 'button is-link' %>
    </div>
    <div class="columns mt-6">
        <div class="column is-4">
            <div class="card">
                <div class="card-header">
                    <div class="card-header-title">
                        Make a withdraw
                    </div>
                </div>
                <div class="card-content">
                    <%= form_with url: withdraw_path(@account), method: :post do |form| %>
                    <div class="field">
                        <%= form.label :no, "Amount", :class => 'label' %>
                        <div class="control">
                            <%= form.text_field :amount, :class => 'input' %>
                        </div>
                        <p class="help">Please enter the amount</p>
                    </div>
                    <%= form.submit "Withdraw", :class => 'button' %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/accounts/show.html.erb
<div class="container">
    <h1 class="title"><%= @account.no %></h1>
    <h2 class="subtitle">
        Account Details
    </h2>
    <div class="mt-4">
        <%= link_to 'Back to Home', accounts_path, :class => 'button is-link' %>
    </div>
    <div class="columns mt-6">
        <div class="column is-4">
            <div class="tile is-parent">
                <article class="tile is-child notification is-link">
                    <div class="content">
                        <p class="title"><%= @account.no %></p>
                        <div class="subtitle">Available Balance <%= @account.balance %></div>
                    </div>
                </article>
            </div>
        </div>
        <div class="column is-8">
            <div class="card">
                <div class="card-header">
                    <div class="card-header-title">
                        Transactions
                    </div>
                </div>
                <div class="card-content">
                    <table class="table is-striped is-fullwidth">
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Description</th>
                                <th>Amount</th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @account.transactions.each do |transaction|%>
                            <tr>
                                <td><%= transaction.created_at.strftime("%F %T") %></td>
                                <% if transaction.amount > 0 %>
                                <td>Deposit</td>
                                <td><%= transaction.amount %></td>
                                <% else %>
                                <td>Withdraw</td>
                                <td><%= transaction.amount * -1 %></td>
                                <% end %>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Bank</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <nav class="navbar is-primary" role="navigation" aria-label="main navigation">
        <div class="navbar-menu">
            <div class="navbar-end">
                <% if user_signed_in? %>
                <p>Logged in as <strong><%= current_user.email %></strong></p>
                <div class="buttons">
                    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-item button is-link' %>
                    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-item button is-danger'  %>
                </div>
                <% else %>
                <div class="buttons">
                    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-item button is-link'  %>
                    <%= link_to "Login", new_user_session_path, :class => 'navbar-item button is-link'  %>
                </div>
                <% end %>
            </div>
        </div>
    </nav>
    <section class="hero">
        <div class="hero-body">
            <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
            <% end %>
            <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
            <% end %>
            <%= yield %>
        </div>
    </section>
</body>

</html>